google-gazzza/algorithm

codewars/5kyu/Calculating Running Total/dongho.sql

[5kyu] Calculating Running Total

---

codewars/5kyu/Calculating Running Total/dongho.sql
codewars/5kyu/MIN, MEDIAN, MAX/dongho.sql
codewars/5kyu/Simple_Hierarchical_structure/dongho.sql

[5kyu] Simple_Hierarchical_structure

---

codewars/5kyu/Calculating Running Total/dongho.sql
codewars/5kyu/MIN, MEDIAN, MAX/dongho.sql
codewars/5kyu/Simple_Hierarchical_structure/dongho.sql
codewars/6kyu/simple_HAVING/dongho.sql
codewars/6kyu/simple_UNION ALL/dongho.sql

[6kyu] simple_UNION ALL

---

codewars/5kyu/Calculating Running Total/dongho.sql
codewars/5kyu/MIN, MEDIAN, MAX/dongho.sql
codewars/5kyu/Simple_Hierarchical_structure/dongho.sql
codewars/6kyu/simple_HAVING/dongho.sql
codewars/6kyu/simple_UNION ALL/dongho.sql
codewars/7kyu/Simple_JOIN_with_COUNT/dongho.sql

[7kyu] Simple_JOIN_with_COUNT

---

baekjoon/easy/1110_sum_cycle/benny.java

주어진 수를 이용해 주어진 수와 똑같은 수가 나올 때가지 더하기를 한 횟수를 출력하는 문제입니다.

[easy]feature/benny_1110

---

baekjoon/easy/10818_min_max/benny.java

주어진 수 중 가장 작은 수와 큰 수를 구하는 문제입니다.

[easy]feature/benny_10818

---

leetcode/easy/67_add_binary/runaway.java

https://leetcode.com/problems/add-binary/

[Easy] 67. Add Binary

---

codewars/7kyu/Maths_with_String_Manipulations/dongho.sql
codewars/8kyu/Convert_to_Hexadecimal/dongho.sql

Maths_with_String_Manipulations

[7kyu] Maths_with_String_Manipulations

---

codewars/7kyu/Maths_with_String_Manipulations/dongho.sql
codewars/7kyu/Simple_JOIN/dongho.sql
codewars/7kyu/Simple_JOIN_with_COUNT/dongho.sql
codewars/8kyu/Convert_to_Hexadecimal/dongho.sql
codewars/8kyu/Simple_SUM/dongho.sql

[8kyu] Simple_SUM

---

codewars/7kyu/Maths_with_String_Manipulations/dongho.sql
codewars/7kyu/Simple_JOIN/dongho.sql
codewars/7kyu/Simple_JOIN_with_COUNT/dongho.sql
codewars/8kyu/Convert_to_Hexadecimal/dongho.sql

[7kyu] Simple_JOIN

---

codewars/7kyu/Counting_and_Grouping/dongho.sql

[7kyu] Counting_and_Grouping

---

codewars/6kyu/Simple_EXISTS/dongho.sql
codewars/8kyu/Adults_only/dongho.sql

[8kyu] Adults_only

---

codewars/6kyu/Simple_EXISTS/dongho.sql

[6kyu] Simple_EXISTS

---

baekjoon/easy/2562_maxvalue_and_index/benny.java

주어진 9개의 자연수 중 최대값과 최대값의 위치를 구하는 문제입니다.

[easy]feature/benny_2562

---

leetcode/easy/69_sqrt/runaway.java

https://leetcode.com/problems/sqrtx/

[Easy] 69. Sqrt(x)

---

codility/easy/1_FrogRiverOne/yalla.java
codility/easy/1_MaxProductOfThree/yalla.java
codility/easy/1_PassingCars/yalla.java
codility/easy/1_PermCheck/yalla.java
codility/easy/1_TapeEquilibrium/yalla.java
codility/easy/1_Triangle/yalla.java

merge before project

---

leetcode/easy/14_longest_common_prefix/runaway.js
leetcode/easy/20_valid_parentheses/runaway.js
leetcode/easy/27_remove_element/runaway.js
leetcode/easy/35_search_insert_position/runaway.js
leetcode/easy/53_maximum_subarray/runaway.java
leetcode/easy/7_reverse_integer/runaway.js
leetcode/easy/9_palindrome_number/runaway.js

leetcode/easy/14_longest_common_prefix
leetcode/easy/20_valid_parentheses
leetcode/easy/27_remove_element
leetcode/easy/35_search_insert_position
leetcode/easy/53_maximum_subarray
leetcode/easy/7_reverse_integer
leetcode/easy/9_palindrome_number

add runaway previous problems

---

leetcode/easy/100_same_tree/runaway.java

https://leetcode.com/problems/same-tree

[Easy] 100. Same Tree

---

leetcode/medium/48_rotate_image/runaway.java

https://leetcode.com/problems/rotate-image/

[medium] 48. Rotate Image

---

leetcode/easy/171_excel_sheet_column_number/hsh2438.py

[Easy] 171. Excel Sheet Column Number

---

leetcode/easy/83_remove_duplicates_from_sorted_list/runaway.java

https://leetcode.com/problems/remove-duplicates-from-sorted-list/

[Easy] 83. Remove Duplicates from Sorted List

---

codewars/6kyu/Simple_JOIN_and_RANK/dongho.sql

[6kyu]  Simple_JOIN_and_RANK

---

leetcode/easy/101_symmetric_tree/runaway.java
leetcode/easy/118_pascals_triangle/runaway.java

https://leetcode.com/problems/symmetric-tree/

[Easy] 101. Symmetric Tree

---

leetcode/easy/118_pascals_triangle/runaway.java

https://leetcode.com/problems/pascals-triangle/

[Easy] 118. Pascal's Triangle

---

leetcode/hard/41_first_missing_positive/dosun.py
leetcode/medium/47_permutations_II/dosun.py

[medium] Solved 47. Permutations II

---

leetcode/easy/119_pascals_triangle_ii/runaway.java

https://leetcode.com/problems/pascals-triangle-ii/

[Easy] 119. Pascal's Triangle II

---

leetcode/easy/88_merge_sorted_array/runaway.java

https://leetcode.com/problems/merge-sorted-array/

[Easy] 88. Merge Sorted Array

---

baekjoon/easy/2577_countNumbers/benny.java

A * B * C의 결과값에 0~9까지의 수가 몇개씩 있는지 세는 문제입니다

[Easy] 2577. count Numbers

---

baekjoon/easy/2562_maxvalue_and_index/benny.java

saekomkr님께서 말씀 주신 함수를 적용해서 
조금 더 간결하게 해보고자 했는데 이런 느낌이 아닌 것 같기도 합니다. ㅜㅜ

[easy]feature/benny_2562 modify

---

leetcode/medium/34_find_first_and_last_position_of_element_in_sorted_array/kdd.hpp

[Medium] Create kdd.hpp on the 34. Find First and Last Position of Element in Sorted Array

---

baekjoon/easy/1546_Sejun_is_a_swindler/benny.java

사기꾼 세준이는 망친 기말고사를 조작해 엄마에게 더 높은 점수를 보여주고자 한다

[Easy] 1546. Sejun is a swindler

---

leetcode/easy/141_linked_list_cycle/runaway.java

https://leetcode.com/problems/linked-list-cycle/

[Easy] 141. Linked List Cycle

---

codewars/7kyu/breaking-chocolate-problem/dduck-breaking-chocolate-problem.js
codewars/7kyu/breaking-chocolate-problem/dduck-breaking-chocolate-problem.py

https://www.codewars.com/kata/534ea96ebb17181947000ada
@koronya js
@netty1010 py
thanks in advance

feat(codewars/7kyu/breaking-chocolate-problem.[js,py])

---

baekjoon/easy/3052_differentRemainderCount/benny.java

값 10개의 나머지를 구한 후 나머지가 서로 다른 수의 갯수를 구하는 문제입니다.

[Easy] 3052. different remainder count

---

baekjoon/easy/8958_OX_Quiz_Score/benny.java

OX퀴즈에서 문제를 연속적으로 맞추면 점수의 가중치를 주어 계산하는 문제입니다.

[Easy] 8958. OX Quiz Score

---

leetcode/easy/14_longest_common_prefix/dduck_14_longest_common_prefix.js

https://leetcode.com/problems/longest-common-prefix/
this is for codereview [PR-42 by koronya](https://github.com/google-gazzza/algorithm/pull/42/files)
@koronya for you

feat(leetcode/top-interview-questions/easy/14_longest_common_prefix.js)

---

codewars/7kyu/numbers-to-letters/dduck-numbers-to-letters.js

https://www.codewars.com/kata/57ebaa8f7b45ef590c00000c
@koronya 
thanks in advance

feat(coding-challange/codewars/7kyu/numbers-to-letters.js)

---

leetcode/medium/36_valid_sudoku/novody.py

Signed-off-by: novody <novody.v.void@gmail.com>

[Medium] 36. Valid Sudoku - novody

---

leetcode/easy/27_remove_element/novody.py

Signed-off-by: novody <novody.v.void@gmail.com>

[Easy] 27. Remove Element - novody

---

leetcode/easy/141_linked_list_cycle/kdd.hpp
leetcode/medium/60_permutation_sequence/kdd.hpp

이번에도 std::next_permutation 편법질을 해서 그런지... 속도가 많이 느리네요 -.-;; 다른 방법도 고민해보겠습니다.

[Medium] Create kdd.hpp on the 60. Permutation Sequence

---

leetcode/easy/13_roman_to_integer/gaebari.java

[easy] 13. Roman to Integer

---

leetcode/easy/50_pow(x, n)/novody.py

Signed-off-by: novody <novody.v.void@gmail.com>

[Easy] 50. Pow(x, n) - novody

---

leetcode/easy/9_palindrome_number/gaebari.java

[easy] 9. Palindrome Number

---

baekjoon/easy/11052_expensive_cards/gaebari.java
baekjoon/easy/11727_rectangular_tiles/gaebari.java
baekjoon/easy/1874_stack_sequence/gaebari.java

update
1874. Stack Sequence
11052. Expensive Cards
11727.Rectangular Tiles

[easy] [baekjoon] 1874 Stack Sequence /  11052. Expensive Cards / 11727.Rectangular Tiles

---

codewars/6kyu/vasya-clerk/vasya-clerk.js

https://www.codewars.com/kata/555615a77ebc7c2c8a0000b8

feat(codewars/6kyu/vasya-clerk.js)

---

codewars/8kyu/alternating-case/dduck-alternating-case.js
codewars/8kyu/alternating-case/dduck-alternating-case.py

https://www.codewars.com/kata/alternating-case-%3C-equals-%3E-alternating-case

feat(codewars/8kyu/alternating-case/alternating-case.[js,py])

---

baekjoon/easy/2743_measure_word_length/gaebari.java

[easy] [baekjoon] 2743. Measure Word Length

[easy] [baekjoon] 2743. Measure Word Length

---

leetcode/easy/21_merge_two_sorted_lists/gaebari.java

[easy] 21. Merge Two Sorted Lists

[easy] 21. Merge Two Sorted Lists

---

leetcode/easy/26_remove_duplicates_from_sorted_array/gaebari.java

[easy] 21. Remove Duplicates From Sorted Array

[easy] 21. Remove Duplicates From Sorted Array

---

leetcode/easy/20_valid_parentheses/gaebari.java

[easy] 20. Valid Parentheses

---

baekjoon/easy/2609_greatest_common_factor_and_least_common_multiple/gaebari.java

[easy] [baekjoon] 2609. Greatest Common Factor AndLeast Common Multiple

[easy] [baekjoon] 2609. Greatest Common Factor AndLeast Common Multiple

---

baekjoon/easy/10430_remainder/gaebari.java

[easy] [baekjoon] 10430. Remainder

[easy] [baekjoon] 10430. Remainder

---

codewars/7kyu/substring-fun/dduck-substring-fun.js
codewars/7kyu/substring-fun/dduck-substring-fun.py

https://www.codewars.com/kata/substring-fun/train/javascript

 feat(coding-challange/codewars/7kyu/substring-fun.[js, py])

---

codewars/7kyu/tail-swap/dduck-tail-swap.js

https://www.codewars.com/kata/tail-swap

feat(codewars/7kyu/tail-swap.js)

---

baekjoon/easy/10808_find_alphabet/gaebari.java

[easy] [baekjoon] 10808. Find Alphabet

[easy] [baekjoon] 10808. Find Alphabet

---

leetcode/hard/10_regular_expression_matching/kdd.hpp

[Hard] Create kdd.hpp on the 10. Regular Expression Matching

---

baekjoon/easy/4344_avgOver/benny.java

하.. 졸려서 막 풀었는데 맘에 안 들어서 내일 리팩토링 해서 다시 커밋하겠습니다.. ㅜㅜ

[Easy] 4344. avgOver

---

codewars/6kyu/longest-alphabetical-substring/dduck-longest-alphabetical-substring.js
codewars/6kyu/longest-alphabetical-substring/dduck-longest-alphabetical-substring.py

https://www.codewars.com/kata/longest-alphabetical-substring
@koronya 
@netty1010 
@systembug @saekomkr 
thanks in advance.
by the way this is my first 6kyu python code
yeay!

feat(codewars/6kyu/longest-alphabetical-substring.js)

---

leetcode/easy/108_convert_sorted_array_to_binary_search_tree/runaway.java

https://leetcode.com/problems/convert-sorted-array-to-binary-search-tree/

[Easy] 108. Convert Sorted Array to Binary Search Tree

---

codewars/8kyu/what-is-between/dduck-what-is-between.js
codewars/8kyu/what-is-between/dduck-what-is-between.py

https://www.codewars.com/kata/what-is-between/train/javascript

 feat(coding-challange/codewars/8kyu/what-is-between.[js, py])

---

leetcode/easy/58_length_of_last_word/gaebari.java

[Easy] 58. Length Of Last Word

[Easy] 58. Length Of Last Word

---

leetcode/easy/278_first_bad_version/dosun.py

python ```Bisection algorithms``` 을 사용했습니다.

[easy] 278. First Bad Version

---

leetcode/easy/7_reverse_integer/gaebari.java

[easy] reverse-integer

---

leetcode/easy/35_search_insert_position/gaebari.java

[Easy] 35. Search Insert Position

[Easy] 35. Search Insert Position

---

leetcode/medium/29_divide_two_integers/hsh2438.py

그냥 while문에서 계속 빼기로 했더니, 시간초과 나네요.
제일 처음에 
if dividend == -2147483648 and divisor == -1:
return 2147483647
이 부분은 문제 오류인 듯 합니다.
2147483648이 결과로 나와야 하는데 2147483647이 나와야 된다고 나오네요.

[Medium] 29. Divide Two Integers

---

codewars/8kyu/regexp-basics-is-it-a-digit/dduck-regexp-basics-is-it-a-digit.js
codewars/8kyu/regexp-basics-is-it-a-digit/dduck-regexp-basics-is-it-a-digit.py

https://www.codewars.com/kata/regexp-basics-is-it-a-digit/

feat(codewars/8kyu/regexp-basics-is-it-a-digit.[js, py])

---

codewars/8kyu/century-from-year/dduck-century-from-year.js
codewars/8kyu/century-from-year/dduck-century-from-year.py
codewars/8kyu/century-from-year/dduck-century-from-year.sql

https://www.codewars.com/kata/century-from-year

 feat(codewars/8kyu/century-from-year.[js, py, sql])

---

leetcode/easy/434_number_of_segments_in_a_string/dosun.py

[easy] 434. Number of Segments in a String

---

codewars/8kyu/draw-stairs/dduck-draw-stairs.js
codewars/8kyu/draw-stairs/dduck-draw-stairs.py

https://www.codewars.com/kata/draw-stairs/

feat(codewars/8kyu/draw-stairs.[js, py])

---

baekjoon/easy/15596_addFunction/benny_15596.java

int형 배열을 받아 모든 값을 더한 후 출력해주는 함수를 만드는 문제입니다

[Easy][baekjoon] 15596. addFunction

---

codewars/8kyu/is-n-divisible-by-x-and-y/dduck-is-n-divisible-by-x-and-y.js
codewars/8kyu/is-n-divisible-by-x-and-y/dduck-is-n-divisible-by-x-and-y.py

https://www.codewars.com/kata/5545f109004975ea66000086

feat(codewars/8kyu/is-n-divisible-by-x-and-y.[js, py])

---

leetcode/easy/66_plus_one/gaebari.java

[Easy] 58. Plus One

---

codewars/7kyu/factorial/dduck-factorial.js
codewars/7kyu/factorial/dduck-factorial.py

https://www.codewars.com/kata/factorial-1/train/javascript

feat(codewars/7kyu/factorial.[js, py])

---

codewars/6kyu/take-a-ten-minute-walk/dduck-take-a-ten-minute-walk.js
codewars/6kyu/take-a-ten-minute-walk/dduck-take-a-ten-minute-walk.py

https://www.codewars.com/kata/take-a-ten-minute-walk/train/javascript
js는 parameter default value로 object(map) 할당시 자연스럽게 초기화 하고 실행이됩니다.
PY같은경우는 dictionary를 할당할 경우 해당 파라미터가 공유가 됩니다.
e.g
```
def test(some_variable={"testKey":0}):
some_variable["testKey"] += 1;
```
test()를 첫 호출하면 밸류 0이지만
두번째 호출하면 0 아닙니다. some_variable공유해서 씁니다.

feat(codewars/6kyu/take-a-ten-minute-walk.[js, py])

---

codewars/7kyu/simple-fun-37-house-numbers-sum/dduck-simple-fun-37-house-numbers-sum.js
codewars/7kyu/simple-fun-37-house-numbers-sum/dduck-simple-fun-37-house-numbers-sum.py

https://www.codewars.com/kata/simple-fun-number-37-house-numbers-sum

feat(codewars/7kyu/simple-fun-37-house-numbers-sum.[js,py])

---

leetcode/medium/78_subsets/dduck_78_subsets.js

it's for review this [pr-168](https://github.com/google-gazzza/algorithm/pull/168)
I tried some nice way for review.
but I couldn't make good one
so I bring some nice algorithm for review.
@koronya @systembug @netty1010

feat(leetcode/medium/78_subsets/dduck_78_subsets.js)

---

codewars/7kyu/santas-naughty-list/dduck-santas-naughty-list.js

https://www.codewars.com/kata/santas-naughty-list

feat(codewars/7kyu/santas-naughty-list.js)

---

leetcode/hard/30_substring_with_concatenation_of_all_words/novody.py

Signed-off-by: novody <novody.v.void@gmail.com>

[Hard] 30. Substring with Concatenation of All Words - novody

---

leetcode/medium/102_binary_tree_level_order_traversal/runaway.java

https://leetcode.com/problems/binary-tree-level-order-traversal/

[Medium] 102. Binary Tree Level Order Traversal

---

leetcode/easy/1046_last_stone_weight/koronya.js

두가지 방식으로 풀었습니다!
처음에는 단순하게 lastStoneWeight2 방식으로 풀다가, 
어 이거 insertionSort 인데? 생각하고
비스무리하게 변형해서 추가 커밋!

[EASY] 1046. Last Stone Weight

---

leetcode/easy/28_implement_strStr/gaebari.java

[Easy] 278. Implement Strstr

---

leetcode/easy/53_maximum_subarray/gaebari.java

[Easy] 53. Maximum Subarray

---

leetcode/easy/70_climbing_stairs/runaway.java

https://leetcode.com/problems/climbing-stairs/

[Easy] 70. Climbing Stairs

---

leetcode/easy/66_plus_one/dduck-66_plus_one.cpp

https://leetcode.com/problems/plus-one/
it's for [PR-301](https://github.com/google-gazzza/algorithm/pull/301/files) review
@systembug it's for you

feat(leetcode/top-interview-questions/easy/66_plus_one.cpp)

---

leetcode/easy/111_minimum_depth_of_binary_tree/runaway.java

https://leetcode.com/problems/minimum-depth-of-binary-tree/

[Easy] 111. Minimum Depth of Binary Tree

---

leetcode/easy/112_path_sum/runaway.java

https://leetcode.com/problems/path-sum/

[Easy] 112. Path Sum

---

codewars/8kyu/alan-patridge-ii-apple-turnover/alan-patridge-ii-apple-turnover.py
codewars/8kyu/alan-patridge-ii-apple-turnover/dduck-alan-patridge-ii-apple-turnover.js

https://www.codewars.com/kata/580a094553bd9ec5d800007d

 feat(codewars/8kyu/alan-patridge-ii-apple-turnover.[js, py])

---

leetcode/easy/107_binary_tree_level_order_traversal_ii/runaway.java

https://leetcode.com/problems/binary-tree-level-order-traversal-ii

[Easy] 107. Binary Tree Level Order Traversal II

---

leetcode/easy/110_balanced_binary_tree/runaway.java

https://leetcode.com/problems/balanced-binary-tree/

[Easy] 110. Balanced Binary Tree

---

codewars/5kyu/interleaving-arrays/dduck-interleaving-arrays.js
codewars/5kyu/interleaving-arrays/dduck-interleaving-arrays.py

https://www.codewars.com/kata/523d2e964680d1f749000135

feat(coding-challange/codewars/5kyu/interleaving-arrays.[js, py]):

---

leetcode/hard/72_edit_distance/dosun.py

https://en.wikibooks.org/wiki/Algorithm_Implementation/Strings/Levenshtein_distance 참고했습니다.

[hard] 72. Edit Distance

---

leetcode/easy/121_best_time_to_buy_and_sell_stock/runaway.java

https://leetcode.com/problems/best-time-to-buy-and-sell-stock/

[Easy] 121. Best Time to Buy and Sell Stock

---

hackerank/easy/dosun.py

rjust 를 사용하여 풀었습니다. 
```
string.rjust(s, width[, fillchar])
```

[easy] Staircase

---

leetcode/easy/206_reverse_linked_list/django.py

recursively 하게 한번 풀어보라 해서 했는데 너무 속도가 느리네여 ㅠ 복잡도는 0.5n^2 인거같습니다

[EASY] 206. Reverse Linked List

---

leetcode/easy/155_min_stack/runaway.java

https://leetcode.com/problems/min-stack/

[Easy] 155. Min Stack

---

hackerank/a_very_big_sum/dosun.py

[easy] A Very Big Sum

---

codewars/8kyu/count-the-monkeys/dduck-count-the-monkeys.js
codewars/8kyu/count-the-monkeys/dduck-count-the-monkeys.py
codewars/8kyu/count-the-monkeys/dduck-count-the-monkeys.rs

https://www.codewars.com/kata/count-the-monkeys/
there is some thing you guys might be interest
@koronya @saekomkr @netty1010 
in rust `(1..n + 1).collect();` return [1, 2,3, ... n+1]
if n = 5, will return [1,2,3,4,5]
and also `(1..=n).collect();` will return [1,2,3,4,5] when n = 5

feat(codewars/8kyu/count-the-monkeys.[js, py, rs])

---

leetcode/easy/1221_split_a_string_in_balanced_strings/ddong.java

https://leetcode.com/problems/split-a-string-in-balanced-strings

[easy] split a string in balanced strings

---

codewars/7kyu/summing-a-numbers-digits/dduck-summing-a-numbers-digits.js
codewars/7kyu/summing-a-numbers-digits/dduck-summing-a-numbers-digits.py

https://www.codewars.com/kata/52f3149496de55aded000410/train/javascript

feat(codewars/7kyu/summing-a-numbers-digits.[js, py])

---

leetcode/easy/1290_convert_binary_number_in_a_linked_list_to_integer/ddong.java

https://leetcode.com/problems/convert-binary-number-in-a-linked-list-to-integer/

[easy] convert_binary_number_in_a_linked_list_to_integer

---

codewars/7kyu/minimize-sum-of-array/dduck-minimize-sum-of-array.js
codewars/7kyu/minimize-sum-of-array/dduck-minimize-sum-of-array.py

https://www.codewars.com/kata/5a523566b3bfa84c2e00010b
너무 졸려서 파이썬 솔루션에 의미없는 코드가 들어갔는데
의미없는 코드 빼면 best practice랑 같아서 그냥 그대로 커밋 했습니다.

feat(codewars/7kyu/minimize-sum-of-array.[js, py])

---

codewars/7kyu/the-wheat-rice-and-chessboard-problem/dduck-the-wheat-rice-and-chessboard-problem.js
codewars/7kyu/the-wheat-rice-and-chessboard-problem/dduck-the-wheat-rice-and-chessboard-problem.py

https://www.codewars.com/kata/5b0d67c1cb35dfa10b0022c7/

feat(codewars/7kyu/the-wheat-rice-and-chessboard-problem.[js, py])

---

codewars/8kyu/on-the-canadian-border-sql-for-beginners-2/dduck-on-the-canadian-border-sql-for-beginners-2.sql

https://www.codewars.com/kata/590ba881fe13cfdcc20001b4/train/sql

feat(codewars/8kyu/on-the-canadian-border-sql-for-beginners-2.sql)

---

leetcode/easy/168_excel_sheet_column_title/runaway.java

https://leetcode.com/problems/excel-sheet-column-title/

[Easy] 168. Excel Sheet Column Title

---

leetcode/easy/771_jewels_and_stones/ddong.java

https://leetcode.com/problems/jewels-and-stones/

[easy] Jewels and Stones

---

codewars/7kyu/arithmetic-progression/dduck-arithmetic-progression.js
codewars/7kyu/arithmetic-progression/dduck-arithmetic-progression.py

https://www.codewars.com/kata/55caf1fd8063ddfa8e000018

feat(codewars/7kyu/arithmetic-progression.[js, py])

---

leetcode/easy/1295_find_numbers_with_even_number_of_digits/ddong.java

https://leetcode.com/problems/find-numbers-with-even-number-of-digits

[easy] find_numbers_with_even_number_of_digits

---

codewars/7kyu/sql-concatenating-columns/dduck-sql-concatenating-columns.sql

https://www.codewars.com/kata/59440034e94fae05b2000073/train/sql
it's for review https://github.com/google-gazzza/algorithm/pull/395

feat(codewars/7kyu/sql-concatenating-columns.sql)

---

leetcode/easy/1207_unique_number_of_occurrences/runaway.java

https://leetcode.com/problems/unique-number-of-occurrences/

[Easy] 1207. Unique Number of Occurrences

---

codewars/7kyu/count-the-divisors-of-a-number/dduck-count-the-divisors-of-a-number.js
codewars/7kyu/count-the-divisors-of-a-number/dduck-count-the-divisors-of-a-number.py

https://www.codewars.com/kata/542c0f198e077084c0000c2e/

feat(codewars/7kyu/count-the-divisors-of-a-number.[js, py])

---

codewars/8kyu/squash-the-bugs/dduck-squash-the-bugs.js
codewars/8kyu/squash-the-bugs/dduck-squash-the-bugs.py

https://www.codewars.com/kata/56f173a35b91399a05000cb7/train/javascript

feat(codewars/8kyu/squash-the-bugs.[js, py])

---

leetcode/easy/561_array_partition_i/leedy1.java

https://leetcode.com/problems/array-partition-i/

[Easy] 561. Array Partition I

---

leetcode/easy/136_single_number/leedy1.java
leetcode/easy/942_di_string_match/leedy1.java

https://leetcode.com/problems/di-string-match/
942번 풀고 실수로 지운 136번 다시 올립니다~

[Easy] 942. DI String Match

---

codewars/8kyu/will-you-make-it/dduck-will-you-make-it.js
codewars/8kyu/will-you-make-it/dduck-will-you-make-it.py

https://www.codewars.com/kata/5861d28f124b35723e00005e

feat(codewars/8kyu/will-you-make-it.[js, py])

---

codewars/6kyu/array-diff/dduck-array-diff.js
codewars/6kyu/array-diff/dduck-array-diff.py

https://www.codewars.com/kata/523f5d21c841566fde000009

feat(codewars/6kyu/array-diff/dduck-array-diff.[js, py])

---

leetcode/easy/136_single_number/leedy1.java
leetcode/easy/942_di_string_match/leedy1.java
leetcode/easy/944_delete_columns_to_make_sorted/leedy1.java

https://leetcode.com/problems/delete-columns-to-make-sorted/

 [Easy] 944. Delete Columns to Make Sorted

---

leetcode/easy/104_maximum_depth_of_binary_tree/runaway.java
leetcode/easy/237_delete_node_in_a_linked_list/runaway.java

https://leetcode.com/problems/maximum-depth-of-binary-tree/
https://leetcode.com/problems/delete-node-in-a-linked-list/

[Easy] 104. Maximum Depth of Binary Tree & 237. Delete Node in a Linked List

---

codewars/8kyu/find-numers-which-are-divisible-by-given-number/dduck-find-numers-which-are-divisible-by-given-number.js
codewars/8kyu/find-numers-which-are-divisible-by-given-number/dduck-find-numers-which-are-divisible-by-given-number.py

https://www.codewars.com/kata/55edaba99da3a9c84000003b/

feat(codewars/8kyu/find-numers-which-are-divisible-by-given-number.[js,py])

---

codility/medium/countNonDivisible/dosun.py

[medium] count_non_divisible

---

leetcode/medium/230_kth_smallest_element_in_a_bst/runaway.java

https://leetcode.com/problems/kth-smallest-element-in-a-bst/

[Medium] 230. Kth Smallest Element in a BST

---

codewars/7kyu/sql-padding-encryption/dduck-sql-padding-encryption.sql

https://www.codewars.com/kata/5943b797d8c9432eb7000066/train/sql
this is for review https://github.com/google-gazzza/algorithm/pull/426/files

feat(codewars/7kyu/sql-padding-encryption.sql)

---

codewars/8kyu/even-or-odd/dduck-even-or-odd.js
codewars/8kyu/even-or-odd/dduck-even-or-odd.sql

https://www.codewars.com/kata/53da3dbb4a5168369a0000fe/
it's for review https://github.com/google-gazzza/algorithm/pull/427/files

feat(codewars/8kyu/even-or-odd.[js,py])

---

codewars/8kyu/sql-basics-mod/dduck-sql-basics-mod.sql

https://www.codewars.com/kata/53da3dbb4a5168369a0000fe/
it's for review https://github.com/google-gazzza/algorithm/pull/437/files

feat(codewars/8kyu/sql-basics-mod.sql)

---

codewars/6kyu/binary-to-text-(ascii)-conversion/dduck-binary-to-text-(ascii)-conversion.js
codewars/6kyu/binary-to-text-(ascii)-conversion/dduck-binary-to-text-(ascii)-conversion.py

https://www.codewars.com/kata/5583d268479559400d000064/

feat(codewars/6kyu/binary-to-text-(ascii)-conversion.[js, py])

---

codewars/8kyu/sql-grasshopper-select-columns/sql-grasshopper-select-columns.sql

https://www.codewars.com/kata/582365c18917435ab3000020/train/sql
it's for review https://github.com/google-gazzza/algorithm/pull/455

feat(codewars/8kyu/sql-grasshopper-select-columns.sql)

---

codewars/7kyu/sql-basics-raise-to-the-power/dduck-sql-basics-raise-to-the-power.sql

https://www.codewars.com/kata/594a8f653b5b4e8f3d000035/train/sql
it's review for https://github.com/google-gazzza/algorithm/pull/456/files

feat(codewars/7kyu/sql-basics-raise-to-the-power.sql)

---

leetcode/easy/1266_minimum_time_visiting_all_points/ddong.java

https://leetcode.com/problems/minimum-time-visiting-all-points/

[easy]minimum-time-visiting-all-points

---

codewars/7kyu/easy-sql-bit-length/dduck-easy-sql-bit-length.sql

https://www.codewars.com/kata/594900e16fd782a607000059/train/sql
it's for review https://github.com/google-gazzza/algorithm/pull/468

feat(codewars/7kyu/easy-sql-bit-length.sql)

---

codewars/7kyu/odd-or-even/dduck-odd-or-even.js
codewars/7kyu/odd-or-even/dduck-odd-or-even.py

https://www.codewars.com/kata/5949481f86420f59480000e7/

feat(codewars/7kyu/odd-or-even/odd-or-even.[js, py])

---

leetcode/easy/190_reverse_bits/runaway.java

https://leetcode.com/problems/reverse-bits/

[Easy] 190. Reverse Bits

---

codewars/6kyu/stringing-me-along/dduck-stringing-me-along.js
codewars/6kyu/stringing-me-along/dduck-stringing-me-along.py

https://www.codewars.com/kata/55f4a44eb72a0fa91600001e
@systembug @koronya @netty1010 
you guys might be interest
maybe is good for compare how implement currying in JS, Py

feat(coding-challange/codewars/6kyu/stringing-me-along.[js, py])

---

codewars/7kyu/sum-of-odd-cubed-numbers/dduck-sum-of-odd-cubed-numbers.js
codewars/7kyu/sum-of-odd-cubed-numbers/dduck-sum-of-odd-cubed-numbers.py

https://www.codewars.com/kata/580dda86c40fa6c45f00028a

feat(coding-challange/codewars/7kyu/sum-of-odd-cubed-numbers.[js, py])

---

leetcode/easy/237_delete_node_in_a_linked_list/kdd.hpp

[Easy] Create kdd.hpp on the 237. Delete Node in a Linked List

---

leetcode/medium/153_find_minimum_in_rotated_sorted_array/hsh2438.py

그냥 min(nums) 반환해도 동작은 하지만, 조금 더 빨라지라고 바이너리 서치를 써봤습니다.

[Medium] 153. Find Minimum in Rotated Sorted Array

---

codewars/7kyu/SQL_with_Harry_Potter_Sorting_Hat_Comparators/dongho.sql

[7kyu] SQL_with_Harry_Potter_Sorting_Hat_Comparators

---

codewars/8kyu/array-plus-array/dduck-array-plus-array.js
codewars/8kyu/array-plus-array/dduck-array-plus-array.py

https://www.codewars.com/kata/5a2be17aee1aaefe2a000151/

feat(codewars/8kyu/array-plus-array.[js, py])

---

codewars/7kyu/youre-a-squre/dduck-youre-a-squre.js
codewars/7kyu/youre-a-squre/dduck-youre-a-squre.py

// https://www.codewars.com/kata/54c27a33fb7da0db0100040e

feat(codewars/7kyu/youre-a-squre.[js, py])

---

codewars/5kyu/memorized-fibonacci/dduck-memorized-fibonacci.js
codewars/5kyu/memorized-fibonacci/dduck-memorized-fibonacci.py

https://www.codewars.com/kata/529adbf7533b761c560004e5
@systembug you might be interest JS solution.

feat(codewars/5kyu/memorized-fibonacci.[js, py])

---

codewars/8kyu/1-find-all-active-student/dduck-1-find-all-active-student.sql

https://www.codewars.com/kata/5809b9ef88b750ab180001ec/train/sql
it's for review https://github.com/google-gazzza/algorithm/pull/498

feat(codewars/8kyu/1-find-all-active-student.sql)

---

codewars/7kyu/easy-sql-absolute-value-and-log-to-base/dduck-easy-sql-absolute-value-and-log-to-base.sql

https://www.codewars.com/kata/594a8f2f7ca3c692a4000041/train/sql
it's review for  https://github.com/google-gazzza/algorithm/pull/508/files

feat(codewars/7kyu/easy-sql-absolute-value-and-log-to-base.sql)

---

codewars/6kyu/fun-with-lists-map/fun-with-lists-map.js

https://www.codewars.com/kata/58259d9062cfb45e1a00006b
@saekomkr you might be interest this explanation

feat(codewars/6kyu/fun-with-lists-map.js)

---

codewars/8kyu/easy-sql-rounding-decimals/dduck-easy-sql-rounding-decimals.sql

https://www.codewars.com/kata/594a6133704e4daf5d00003d/train/sql
it's for review https://github.com/google-gazzza/algorithm/pull/485/files

feat(codewars/8kyu/easy-sql-rounding-decimals.sql)

---

codewars/7kyu/product-of-maximums-of-array-(array-series-2)/dduck-product-of-maximums-of-array-(array-series-2).js
codewars/7kyu/product-of-maximums-of-array-(array-series-2)/dduck-product-of-maximums-of-array-(array-series-2).py

https://www.codewars.com/kata/5a63948acadebff56f000018

feat(codewars/7kyu/product-of-maximums-of-array-(array-series-2).[js, py])

---

codewars/7kyu/sql-with-sailor-moon-thinking-about-joins/dduck-sql-with-sailor-moon-thinking-about-joins.sql

https://www.codewars.com/kata/5ab7a736edbcfc8e62000007/train/sql
it's for review https://github.com/google-gazzza/algorithm/pull/521/files

feat(codewars/7kyu/sql-with-sailor-moon-thinking-about-joins.sql)

---

leetcode/easy/1047_remove_all_adjacent_duplicates_in_string/leedy1.java

https://leetcode.com/problems/remove-all-adjacent-duplicates-in-string/

[Easy] 1047. Remove All Adjacent Duplicates In String

---

codewars/7kyu/array-leaders-(array-series-3)/dduck-array-leaders-(array-series-3).js
codewars/7kyu/array-leaders-(array-series-3)/dduck-array-leaders-(array-series-3).py

https://www.codewars.com/kata/5a651865fd56cb55760000e0

feat(codewars/7kyu/array-leaders-(array-series-3).[js, py])

---

codewars/7kyu/grocery-store-support-local-products/dduck-grocery-store-support-local-products.sql

https://www.codewars.com/kata/5a8ed96bfd8c066e7f00011a/train/sql
it's review for https://github.com/google-gazzza/algorithm/pull/542/files

feat(codewars/7kyu/grocery-store-support-local-products.sql)

---

leetcode/easy/1078_occurrences_after_bigram/leedy1.java

https://leetcode.com/problems/occurrences-after-bigram/

[Easy] 1078. Occurrences After Bigram

---

codewars/7kyu/array-leaders-(array-series-4)/dduck-array-leaders-(array-series-4).js
codewars/7kyu/array-leaders-(array-series-4)/dduck-array-leaders-(array-series-4).py

https://www.codewars.com/kata/5a7893ef0025e9eb50000013/

feat(codewars/7kyu/array-leaders-(array-series-4).[js, py])

---

codewars/7kyu/sql-basics-truncating/dduck-sql-basics-truncating.sql

https://www.codewars.com/kata/594a8fa5a2db9e5f290000c3/train/sql
it's for review https://github.com/google-gazzza/algorithm/pull/543/files

feat(codewars/7kyu/sql-basics-truncating.sql)

---

codewars/7kyu/array-leaders-(array-series-5)/dduck-array-leaders-(array-series-5).js
codewars/7kyu/array-leaders-(array-series-5)/dduck-array-leaders-(array-series-5).py

https://www.codewars.com/kata/5a905c2157c562994900009d

feat(codewars/7kyu/array-leaders-(array-series-5).[js, py])

---

codewars/7kyu/sql-with-harry-potter-sorting-hat-comparators/dduck-sql-with-harry-potter-sorting-hat-comparators.sql

https://www.codewars.com/kata/5abcf0f930488ff1a6000b66/train/sql
it's review for https://github.com/google-gazzza/algorithm/pull/562/files

feat(codewars/7kyu/sql-with-harry-potter-sorting-hat-comparators.sql)

---

leetcode/easy/1299_replace_elements_with_greatest_element_on_right_side/koronya.js

첫 풀이는 replaceElements3 대로 풀이.
이것에서 약간 향상시키려는 의도로 replaceElements2 대로 풀이.
하지만, 예상만큼 향상되지는 않음 -_-;
아예 단순 무식하게 하면 얼마나 느린가 보자, 라고 해서 나온게 replaceElements4
최종적으로는 replaceElements 대로 풀이!

[EASY] 1299. Replace Elements with Greatest Element on Right Side - 총 4가지의 방법으로 풀이해봄!

---

codewars/7kyu/array-leaders-(array-series-6)/dduck-array-leaders-(array-series-6).js
codewars/7kyu/array-leaders-(array-series-6)/dduck-array-leaders-(array-series-6).py

https://www.codewars.com/kata/5a91a7c5fd8c061367000002/

feat(codewars/7kyu/array-leaders-(array-series-6).[js, py])

---

codewars/7kyu/easy-sql-cube-root-and-natual-log/dduck-easy-sql-cube-root-and-natual-log.sql

https://www.codewars.com/kata/594a6ad320ac16a54400007f
it' for review https://github.com/google-gazzza/algorithm/pull/596/files

feat(codewars/7kyu/easy-sql-cube-root-and-natual-log.sql)

---

leetcode/easy/442_find_all_duplicates_in_an_array/leedy.java

https://leetcode.com/problems/find-all-duplicates-in-an-array/

[Easy] 442. Find All Duplicates in an Array

---

codewars/7kyu/array-leaders-(array-series-7)/dduck-array-leaders-(array-series-7).js
codewars/7kyu/array-leaders-(array-series-7)/dduck-array-leaders-(array-series-7).py

https://www.codewars.com/kata/5aa1bcda373c2eb596000112/javascript

feat(codewars/7kyu/array-leaders-(array-series-7).[js, py])

---

codewars/7kyu/sql-disorder/dduck-sql-disorder.sql

https://www.codewars.com/kata/59cb550486a6fd10b50000ad/train/sql
it's for review https://github.com/google-gazzza/algorithm/pull/597/files

feat(codewars/7kyu/sql-disorder.sql)

---

codewars/8kyu/convert-number-to-reversed-array-of-digits/dduck-convert-number-to-reversed-array-of-digits.js
codewars/8kyu/convert-number-to-reversed-array-of-digits/dduck-convert-number-to-reversed-array-of-digits.py

https://www.codewars.com/kata/5583090cbe83f4fd8c000051

feat(codewars/8kyu/convert-number-to-reversed-array-of-digits.[js, py])

---

codewars/7kyu/row-weights/dduck-row-weights.js
codewars/7kyu/row-weights/dduck-row-weights.py

https://www.codewars.com/kata/5abd66a5ccfd1130b30000a9

feat(codewars/7kyu/row-weights.[js, py])

---

leetcode/easy/1299_replace_elements_with_greatest_element_on_right_side/dduck-1299_replace_elements_with_greatest_element_on_right_side.js

https://leetcode.com/problems/replace-elements-with-greatest-element-on-right-side/submissions/
it's for review https://github.com/google-gazzza/algorithm/pull/624/files
@koronya

feat(leetcode/easy/1299_replace_elements_with_greatest_element_on_right_side.js)

---

leetcode/easy/234_palindrome_linked_list/django.py

https://leetcode.com/problems/palindrome-linked-list/

[EASY] 234. Palindrome Linked List [py]

---

codewars/7kyu/remove-duplicate-words/dduck-remove-duplicate-words.js
codewars/7kyu/remove-duplicate-words/dduck-remove-duplicate-words.py

https://www.codewars.com/kata/5b39e3772ae7545f650000fc

feat(codewars/7kyu/remove-duplicate-words.[js, py])

---

leetcode/easy/two-sum-ii-input-array-is-sorted/dduck-two-sum-ii-input-array-is-sorted.js
leetcode/easy/two-sum-ii-input-array-is-sorted/dduck-two-sum-ii-input-array-is-sorted.py

https://leetcode.com/problems/two-sum-ii-input-array-is-sorted/
it's review for https://github.com/google-gazzza/algorithm/pull/548
@sigmarion1

feat(leetcode/easy/two-sum-ii-input-array-is-sorted.[js, py])

---

leetcode/easy/884_uncommon_words_from_two_sentences/leedy1.java

https://leetcode.com/problems/uncommon-words-from-two-sentences/

[Easy] 884. Uncommon Words from Two Sentences

---

leetcode/easy/263_ugly_number/django.py

https://leetcode.com/problems/ugly-number/

[EASY] 263. Ugly Number [py]

---

codewars/6kyu/are-they-the-same/dduck-are-they-the-same.js
codewars/6kyu/are-they-the-same/dduck-are-they-the-same.py

https://www.codewars.com/kata/550498447451fbbd7600041c

feat(codewars/6kyu/are-they-the-same.[js, py])

---

codewars/7kyu/balanced-number-special-numbers-series-#1/dduck-balanced-number-special-numbers-series-#1.js
codewars/7kyu/balanced-number-special-numbers-series-#1/dduck-balanced-number-special-numbers-series-#1.py

https://www.codewars.com/kata/5a4e3782880385ba68000018

feat(codewars/7kyu/balanced-number-special-numbers-series-#1.[js, py])

---

codewars/8kyu/no-loops-2-you-only-need-one/dduck-no-loops-2-you-only-need-one.js
codewars/8kyu/no-loops-2-you-only-need-one/dduck-no-loops-2-you-only-need-one.py

https://www.codewars.com/kata/57cc40b2f8392dbf2a0003ce

feat(codewars/8kyu/no-loops-2-you-only-need-one.[js, py])

---

leetcode/easy/896_monotonic_array/dduck-896_monotonic_array.js

https://leetcode.com/problems/monotonic-array
it's for review https://github.com/google-gazzza/algorithm/pull/552/files
@saekomkr 
제가 푼 로직을 수도코드?로 표현하자면
```
make new-array from input-array:
return math sign (input-array[i-1] - input-array[i]
and there will be only three type of these [-1, 0, 1]
convert  to set -> new Set(new-array)
if set size is 1 or 2. is monotonic.
if three. is not monotonic
```

feat(leetcode/easy/896_monotonic_array.js)

---

leetcode/easy/268_missing_number/django.py

https://leetcode.com/problems/missing-number/

[EASY] 268. Missing Number [py]

---

leetcode/easy/500_keyboard_row/dduck_500_keyboard_row.js

https://leetcode.com/problems/keyboard-row/
it's for review https://github.com/google-gazzza/algorithm/pull/634/files
@leedy1

feat(leetcode/easy/500_keyboard_row.js)

---

codewars/7kyu/special-number-(special-numbers-series-#5)/dduck-special-number-(special-numbers-series-#5).js
codewars/7kyu/special-number-(special-numbers-series-#5)/dduck-special-number-(special-numbers-series-#5).py

https://www.codewars.com/kata/5a55f04be6be383a50000187/

feat(codewars/7kyu/special-number-(special-numbers-series-#5).[js, py])

---

codewars/8kyu/area-or-perimeter/dduck-area-or-perimeter.js
codewars/8kyu/area-or-perimeter/dduck-area-or-perimeter.py

https://www.codewars.com/kata/5ab6538b379d20ad880000ab

feat(codewars/8kyu/area-or-perimeter.[js, py])

---

leetcode/easy/290_word_pattern/django.py

https://leetcode.com/problems/word-pattern/

[EASY] 290. Word Pattern [py]

---

codewars/7kyu/easy-sql-moving-values/dduck-easy-sql-moving-values.sql

https://www.codewars.com/kata/594a389387a7c6a77a000005
it's for review https://github.com/google-gazzza/algorithm/pull/628

feat(codewars/7kyu/easy-sql-moving-values.sql)

---

codewars/7kyu/strongn-strong-number-(special-numbers-series-#2)/dduck-strongn-strong-number-(special-numbers-series-#2).js
codewars/7kyu/strongn-strong-number-(special-numbers-series-#2)/dduck-strongn-strong-number-(special-numbers-series-#2).py

https://www.codewars.com/kata/5a4d303f880385399b000001

feat(codewars/7kyu/strongn-strong-number-(special-numbers-series-#2).[js, py]) 

---

codewars/7kyu/re-open-class/dduck-re-open-class.js

https://www.codewars.com/kata/53d628de83db278fb1000710

feat(codewars/7kyu/re-open-class.js)

---

leetcode/easy/14_longest_common_prefix/dosun.scala
leetcode/easy/989_add_to_array-Form_of_integer/dosun.scala

[easy] 989. Add to Array-Form of Integer

---

leetcode/easy/258_add-digits/dosun.scala

Follow up:
Could you do it without any loop/recursion in O(1) runtime?

[easy] 258. Add Digits

---

leetcode/easy/463_island_perimeter/leedy1.java
leetcode/easy/682_baseball_game/leedy1.java

https://leetcode.com/problems/island-perimeter/

[Easy] 463. Island Perimeter

---

leetcode/easy/682_baseball_game/leedy1.java

https://leetcode.com/problems/baseball-game/

[Easy] 682. Baseball Game

---

codewars/7kyu/jumping-number-(special-numbers-series-#4)/dduck-jumping-number-(special-numbers-series-#4).js
codewars/7kyu/jumping-number-(special-numbers-series-#4)/dduck-jumping-number-(special-numbers-series-#4).py

https://www.codewars.com/kata/5a54e796b3bfa8932c0000ed/train/javascript

feat(codewars/7kyu/jumping-number-(special-numbers-series-#4).[js, py])

---

codewars/8kyu/Grasshopper_Check_for_factor/dongho.sql

[8kyu] Grasshopper_Check_for_factor

---

leetcode/easy/50_pow/dosun.scala

[easy] 50. Pow(x, n)

---

leetcode/easy/278_first_bad_version/django.py

https://leetcode.com/problems/first-bad-version/

[EASY] 278. First Bad Version [py]

---

codewars/8kyu/grasshopper-messi-goals-function/dduck-grasshopper-messi-goals-function.sql

https://www.codewars.com/kata/55f73be6e12baaa5900000d4
it's review for https://github.com/google-gazzza/algorithm/pull/639

feat(codewars/8kyu/grasshopper-messi-goals-function.sql)

---

codewars/7kyu/disarium-number-(special-numbers-series-#3)/dduck-disarium-number-(special-numbers-series-#3).js
codewars/7kyu/disarium-number-(special-numbers-series-#3)/dduck-disarium-number-(special-numbers-series-#3).py

https://www.codewars.com/kata/5a53a17bfd56cb9c14000003/

feat(codewars/7kyu/disarium-number-(special-numbers-series-#3).[js, py])

---

leetcode/easy/657_robot_return_to_origin/ddong.java

https://leetcode.com/problems/robot-return-to-origin

[easy] robot-return-to-origin

---

leetcode/easy/961_n-repeated_element_in_size_2n_array/dduck-961_n-repeated_element_in_size_2n_array.js

https://leetcode.com/problems/n-repeated-element-in-size-2n-array/
it's review for https://github.com/google-gazzza/algorithm/pull/650/files
@koronya 
전 가장 많은 value가진애 찾는건가 하고 일단 후다닥 풀고나서
@koronya 님 문제 푼거보고 아~ N+1 Uniq였구나~ 하고 무릎 탁 쳤습니다.
그런데 개인적으로 for of는 선호하지 않고 또 같은방식으로 풀순 없어서
성능이 얼추 비슷한 선에서 some으로 풀어봤습니다.

feat(leetcode/easy/961_n-repeated_element_in_size_2n_array.js)

---

leetcode/easy/292_nim_game/django.py

https://leetcode.com/problems/nim-game/

[EASY] 292. Nim Game [py]

---

leetcode/easy/1342_number_of_steps_to_reduce_a_number_to_zero/dosun.scala

1342. Number of Steps to Reduce a Number to Zero

[easy] 1342. Number of Steps to Reduce..

---

leetcode/easy/205_isomorphic_strings/runaway.java

https://leetcode.com/problems/isomorphic-strings/

[Easy] 205. Isomorphic Strings

---

codewars/6kyu/sql-basics-top-10-customers-by-total-payments-amount/dduck-sql-basics-top-10-customers-by-total-payments-amount.sql

https://www.codewars.com/kata/580d08b5c049aef8f900007c/train/sql
it's for review https://github.com/google-gazzza/algorithm/pull/641/files

feat(codewars/6kyu/sql-basics-top-10-customers-by-total-payments-amount.sql)

---

codewars/7kyu/tidy-number-(special-number-seires-9)/dduck-tidy-number-(special-number-seires-9).js
codewars/7kyu/tidy-number-(special-number-seires-9)/dduck-tidy-number-(special-number-seires-9).py

https://www.codewars.com/kata/5a87449ab1710171300000fd/train/javascript

feat(codewars/7kyu/tidy-number-(special-number-seires-9).[js, py])

---

leetcode/easy/204_count_primes/runaway.java

https://leetcode.com/problems/count-primes

 [Easy] 204. Count Primes

---

leetcode/easy/171_excel_sheet_column_number/dduck_171_excel_sheet_column_number.js
leetcode/easy/171_excel_sheet_column_number/dduck_171_excel_sheet_column_number.py

https://leetcode.com/problems/excel-sheet-column-number
it's for review https://github.com/google-gazzza/algorithm/pull/567
@jmp7786

feat(leetcode/easy/171_excel_sheet_column_number.[js, py])

---

leetcode/easy/299_bulls_and_cows/django.py

https://leetcode.com/problems/bulls-and-cows/

[EASY] 299. Bulls and Cows [py]

---

codewars/7kyu/extra-perfect-numbers-(special-numbers-series-7)/dduck-extra-perfect-numbers-(special-numbers-series-7).js
codewars/7kyu/extra-perfect-numbers-(special-numbers-series-7)/dduck-extra-perfect-numbers-(special-numbers-series-7).py

https://www.codewars.com/kata/5a662a02e626c54e87000123

feat(codewars/7kyu/extra-perfect-numbers-(special-numbers-series-7).[js, py])

---

leetcode/easy/507_perfect_number/koronya.js

처음에 checkPerfectNumber3처럼 풀었다가...(860ms)
checkPerfectNumber2처럼 풀었다가...(460ms)
최종적으로 checkPerfectNumber 처럼 풀이!(56ms!)

[EASY] 507. Perfect Number

---

codewars/7kyu/growth-of-a-population/dduck-growth-of-a-population.cpp
codewars/7kyu/growth-of-a-population/dduck-growth-of-a-population.js
codewars/7kyu/growth-of-a-population/dduck-growth-of-a-population.py

https://www.codewars.com/kata/563b662a59afc2b5120000c6

feat(codewars/7kyu/growth-of-a-population.[js, py, cpp])

---

codewars/7kyu/automorphic-number-(special-numbers-series-#6)/dduck-automorphic-number-(special-numbers-series-#6).js
codewars/7kyu/automorphic-number-(special-numbers-series-#6)/dduck-automorphic-number-(special-numbers-series-#6).py

https://www.codewars.com/kata/5a58d889880385c2f40000aa/

feat(codewars/7kyu/automorphic-number-(special-numbers-series-#6).[js, py])

---

leetcode/medium/50_powx_n/dduck_50_powx_n.js
leetcode/medium/50_powx_n/dduck_50_powx_n.py

https://leetcode.com/problems/powx-n/
it's for review https://github.com/google-gazzza/algorithm/pull/709 and https://github.com/google-gazzza/algorithm/pull/709
for @netty1010 @hsh2438

feat(leetcode/medium/50_powx_n.[js, ps])

---

codewars/6kyu/break-camel-case/dduck-break-camel-case.js
codewars/6kyu/break-camel-case/dduck-break-camel-case.py

https://www.codewars.com/kata/5208f99aee097e6552000148/

feat(codewars/6kyu/break-camel-case.[js, py])

---

codewars/7kyu/sql-bytes-in-string-from-ints/dduck-sql-bytes-in-string-from-ints.sql

https://www.codewars.com/kata/59491429952ac97ad9000106/train/sql
it's for review https://github.com/google-gazzza/algorithm/pull/716/files

feat(codewars/7kyu/sql-bytes-in-string-from-ints.sql)

---

leetcode/easy/342_power_of_four/django.py

https://leetcode.com/problems/power-of-four/

[EASY] 342. Power of Four [py]\

---

codewars/6kyu/reducing-by-steps/dduck-reducing-by-steps.js

https://www.codewars.com/kata/56efab15740d301ab40002ee

feat(codewars/6kyu/reducing-by-steps.js)

---

codewars/8kyu/grasshopper-check-for-factor/dduck-grasshopper-check-for-factor.sql

https://www.codewars.com/kata/55cbc3586671f6aa070000fb
it's for review https://github.com/google-gazzza/algorithm/pull/717

feat(codewars/8kyu/grasshopper-check-for-factor.sql)

---

leetcode/easy/442_find_all_duplicates_in_an_array/koronya.js

findDuplicates3
풀이대로 하면, 잘못된 풀이.
문제의 제약사항!
Could you do it without extra space and in O(n) runtime?

[MEDIUM] 442. Find All Duplicates in an Array

---

codewars/7kyu/regexp-basics-is-it-a-eight-bit-unsigned-number/dduck-regexp-basics-is-it-a-eight-bit-unsigned-number.js

https://www.codewars.com/kata/567e8f7b4096f2b4b1000005/train/javascript

feat(codewars/7kyu/regexp-basics-is-it-a-eight-bit-unsigned-number.js)

---

codewars/6kyu/counting-duplicates/dduck-counting-duplicates.js

https://www.codewars.com/kata/54bf1c2cd5b56cc47f0007a1

feat(codewars/6kyu/counting-duplicates.js)

---

codewars/7kyu/calculator-coin-combination/dduck-calculator-coin-combination.js

https://www.codewars.com/kata/564d0490e96393fc5c000029/

feat(codewars/7kyu/calculator-coin-combination.js)

---

codewars/7kyu/pandemia/dduck-pandemia.js

https://www.codewars.com/kata/5e2596a9ad937f002e510435/solutions/javascript

feat(codewars/7kyu/pandemia.js)

---

leetcode/easy/225_implement_stack_using_queues/runaway.java

https://leetcode.com/problems/implement-stack-using-queues/

[Easy] 225. Implement Stack using Queues

---

leetcode/easy/226_invert_binary_tree/runaway.java

https://leetcode.com/problems/invert-binary-tree/

[Easy] 226. Invert Binary Tree

---

codewars/7kyu/selective-fear-of-numbers/dduck-selective-fear-of-numbers.js
codewars/7kyu/selective-fear-of-numbers/dduck-selective-fear-of-numbers.py

https://www.codewars.com/kata/55b1fd84a24ad00b32000075/

feat(codewars/7kyu/selective-fear-of-numbers.[js, py])

---

leetcode/easy/231_power_of_two/runaway.java

https://leetcode.com/problems/power-of-two/

[Easy] 231. Power of Two

---

leetcode/easy/551_student_attendance_record/dduck_551_student_attendance_record.js

https://leetcode.com/problems/student-attendance-record-i/
it's for review https://github.com/google-gazzza/algorithm/pull/808/files
@netty1010

feat(leetcode/easy/551_student_attendance_record.js)

---

codewars/7kyu/polydivisible-numbers/dduck-polydivisible-numbers.js
codewars/7kyu/polydivisible-numbers/dduck-polydivisible-numbers.py

https://www.codewars.com/kata/5e4217e476126b000170489b/

feat(codewars/7kyu/polydivisible-numbers.[js, py])

---

codewars/7kyu/string-ends-with/dduck-string-ends-with.js
codewars/7kyu/string-ends-with/dduck-string-ends-with.py

https://www.codewars.com/kata/51f2d1cafc9c0f745c00037d

feat(codewars/7kyu/string-ends-with.[js, py])

---

codewars/7kyu/sort-out-the-men-from-boys/dduck-sort-out-the-men-from-boys.cpp
codewars/7kyu/sort-out-the-men-from-boys/dduck-sort-out-the-men-from-boys.js
codewars/7kyu/sort-out-the-men-from-boys/dduck-sort-out-the-men-from-boys.py

https://www.codewars.com/kata/563b662a59afc2b5120000c6

feat(codewars/7kyu/sort-out-the-men-from-boys.[js, py, cpp])

---

leetcode/easy/1309_decrypt_string../dosun.scala

1309. Decrypt String from Alphabet to Integer Mapping

[easy] 1309. Decrypt String from Alphabet..

---

codewars/6kyu/buying-a-car/dduck-buying-a-car.cpp
codewars/6kyu/buying-a-car/dduck-buying-a-car.js
codewars/6kyu/buying-a-car/dduck-buying-a-car.py
codewars/6kyu/buying-a-car/dduck-buying-a-car.sc

https://www.codewars.com/kata/554a44516729e4d80b000012
you guys might be interest
I think it's good example for compare each language
@saekomkr @netty1010 @koronya @hsh2438

feat(codewars/6kyu/buying-a-car.[cpp, js, py, sc])

---

leetcode/easy/176_second_highest_salary/runaway.sql

https://leetcode.com/problems/second-highest-salary/

[Easy] 176. Second Highest Salary

---

leetcode/easy/575_distribute_candies/leedy.java

https://leetcode.com/problems/distribute-candies/

[Easy] 575. Distribute Candies

---

leetcode/easy/412_fizz_buzz/leedy1.java

https://leetcode.com/problems/fizz-buzz/

[Easy] 412. Fizz Buzz

---

leetcode/easy/1281_subtract_the_product/dosun.scala

1281. Subtract the Product and Sum of Digits of an Integer

[easy] 1281. Subtract the Product and Sum..

---

codewars/7kyu/two-oldest-ages/dduck-two-oldest-ages.js
codewars/7kyu/two-oldest-ages/dduck-two-oldest-ages.py

https://www.codewars.com/kata/511f11d355fe575d2c000001/train/javascript

feat(codewars/7kyu/two-oldest-ages.[js, py])

---

leetcode/easy/1324_print_words_vertically/leedy1.java

https://leetcode.com/problems/print-words-vertically/

[Easy] 1324. Print Words Vertically

---

leetcode/easy/392_is_subsequence/kdd.hpp

음.. Leetcode C++ 컴파일러가 이상한 건지, 원래는 거의 똑같은 속도로 10ms 내외로 떨어져야 할 게 실질적으로는 다르게 처리되네요. -.-;; STL 쓴다고 해도 오버헤드가 거의 없거나 constexpr이나 template 최적화 등으로 아예 없어야 할텐데...;;; 최근에 풀었던 문제들도 뭔가 좀 이상하네요.

[Easy] Create kdd.hpp on the 392. Is Subsequence

---

codewars/7kyu/see-you-next-happy-year/dduck-see-you-next-happy-year.js

https://www.codewars.com/kata/5ae7e3f068e6445bc8000046

feat(codewars/7kyu/see-you-next-happy-year.js)

---

leetcode/easy/175_combine_two_tables/runaway.sql

https://leetcode.com/problems/combine-two-tables/submissions/

[Easy] 175. Combine Two Tables

---

codewars/6kyu/equal-sides-of-an-array/dduck-equal-sides-of-an-array.js
codewars/6kyu/equal-sides-of-an-array/dduck-equal-sides-of-an-array.py

https://www.codewars.com/kata/5679aa472b8f57fb8c000047

feat(codewars/6kyu/equal-sides-of-an-array.[js, py])

---

codewars/7kyu/complete-the-pattern-1/dduck-complete-the-pattern-1.js
codewars/7kyu/complete-the-pattern-1/dduck-complete-the-pattern-1.py

https://www.codewars.com/kata/5572f7c346eb58ae9c000047/

feat(codewars/7kyu/complete-the-pattern-1.[js, py])

---

codewars/7kyu/magic-index/dduck-magic-index.js

https://www.codewars.com/kata/57d5fed61a6282bf6f002a5f

feat(codewars/7kyu/magic-index.js)

---

codewars/7kyu/from-the-minimum/dduck-from-the-minimum.cpp
codewars/7kyu/from-the-minimum/dduck-from-the-minimum.js
codewars/7kyu/from-the-minimum/dduck-from-the-minimum.py

https://www.codewars.com/kata/563b662a59afc2b5120000c6

feat(codewars/7kyu/from-the-minimum.[cpp, js, py])

---

leetcode/easy/804_unique_morse_code_words/dduck_804_unique_morse_code_words.js
leetcode/easy/804_unique_morse_code_words/dduck_804_unique_morse_code_words.sc

https://leetcode.com/problems/unique-morse-code-words/
it's for review https://github.com/google-gazzza/algorithm/pull/858
@netty1010 
@koronya

feat(leetcode/easy/804_unique_morse_code_words.[sc, js])

---

codewars/6kyu/duplicate-encoder/dduck-duplicate-encoder.js
codewars/6kyu/duplicate-encoder/dduck-duplicate-encoder.py

https://www.codewars.com/kata/54b42f9314d9229fd6000d9c/train/javascript

feat(codewars/6kyu/duplicate-encoder.[js, py])

---

leetcode/easy/824_goat_latin/leedy1.java

https://leetcode.com/problems/goat-latin/

[Easy] 824. Goat Latin

---

codewars/6kyu/detect-pangram/dduck-detect-pangram.js
codewars/6kyu/detect-pangram/dduck-detect-pangram.py

https://www.codewars.com/kata/545cedaa9943f7fe7b000048/train/javascript

feat(codewars/6kyu/detect-pangram.[js, py])

---

leetcode/easy/181_employees_earning_more_than_their_managers/runaway.sql

https://leetcode.com/problems/employees-earning-more-than-their-managers/

[Easy] 181. Employees Earning More Than Their Managers

---

codewars/6kyu/stop-gninnips-my-sdrow/dduck-stop-gninnips-my-sdrow.cpp
codewars/6kyu/stop-gninnips-my-sdrow/dduck-stop-gninnips-my-sdrow.js
codewars/6kyu/stop-gninnips-my-sdrow/dduck-stop-gninnips-my-sdrow.py
codewars/6kyu/stop-gninnips-my-sdrow/dduck-stop-gninnips-my-sdrow.sc

https://www.codewars.com/kata/563b662a59afc2b5120000c6
@systembug 
그동안 리뷰 달아주신 내용을 최대한 반영하려고 했는데 마음에 드실지 모르겠네요 😅
여러분... 씨쁠쁠 하세요...

feat(codewars/6kyu/stop-gninnips-my-sdrow.[cpp, js, py, sc])

---

codewars/5kyu/weight-for-weight/dduck-weight-for-weight.js
codewars/5kyu/weight-for-weight/dduck-weight-for-weight.py
codewars/5kyu/weight-for-weight/dduck-weight-for-weight.sc

https://www.codewars.com/kata/55c6126177c9441a570000cc
@hsh2438 you might be interest this

feat(codewars/5kyu/weight-for-weight.[js, py, sc])

---

codewars/7kyu/alternate-capitalization/dduck-alternate-capitalization.js
codewars/7kyu/alternate-capitalization/dduck-alternate-capitalization.py

https://www.codewars.com/kata/59cfc000aeb2844d16000075/

feat(codewars/7kyu/alternate-capitalization.[js, py])

---

leetcode/easy/1189_maximum_number_of_balloons/leedy1.java

https://leetcode.com/problems/maximum-number-of-balloons/

[Easy] 1189. Maximum Number of Balloons

---

.gitignore
leetcode/easy/509_fibonacci_number/dosun.py

- memorization
- python decorator 사용

[easy] 509. Fibonacci Number

---

leetcode/easy/182_duplicate_emails/runaway.sql

https://leetcode.com/problems/duplicate-emails/submissions/

[Easy] 182. Duplicate Emails

---

leetcode/easy/183_customers_who_never_order/runaway.sql

https://leetcode.com/problems/customers-who-never-order/

[Easy] 183. Customers Who Never Order

---

leetcode/easy/196_delete_duplicate_emails/runaway.sql

https://leetcode.com/problems/delete-duplicate-emails/submissions/

[Easy] 196. Delete Duplicate Emails

---

leetcode/easy/1089_duplicate_zeros/leedy1.java

https://leetcode.com/problems/duplicate-zeros/

[Easy] 1089. Duplicate Zeros

---

leetcode/easy/595_big_countries/runaway.sql

https://leetcode.com/problems/big-countries/

[Easy] 595. Big Countries

---

leetcode/easy/596_classes_more_than_5_students/runaway.sql

https://leetcode.com/problems/classes-more-than-5-students/

[Easy] 596. Classes More Than 5 Students

---

leetcode/easy/197_rising_temperature/runaway.sql

https://leetcode.com/problems/rising-temperature/

[Easy] 197. Rising Temperature

---

leetcode/easy/1009_complement_of_base_10_integer/leedy1.java

https://leetcode.com/problems/complement-of-base-10-integer/submissions/

[Easy] 1009. Complement of Base 10 Integer

---

leetcode/easy/693_binary_number_with_alternating_bits/leedy1.java

https://leetcode.com/problems/binary-number-with-alternating-bits/submissions/

[Easy] 693. Binary Number with Alternating Bits

---

leetcode/medium/5_longest_palindromic_substring/runaway.js

https://leetcode.com/problems/longest-palindromic-substring/

[leetcode-medium, js] 5. Longest Palindromic Substring

---

leetcode/medium/6_zigzag_conversion/runaway.js

https://leetcode.com/problems/zigzag-conversion/

[leetcode-medium, js] 6. ZigZag Conversion

---

codewars/6kyu/rectangle-into-squares/dduck-rectangle-into-squares.js
codewars/6kyu/rectangle-into-squares/dduck-rectangle-into-squares.py

https://www.codewars.com/kata/55466989aeecab5aac00003e

feat(codewars/6kyu/rectangle-into-squares.[js, py])

---

leetcode/medium/55_jump_game/runaway.js

https://leetcode.com/problems/jump-game/

[leetcode-medium, js] 55. Jump Game

---

codewars/6kyu/mexican-wave/dduck-mexican-wave.js
codewars/6kyu/mexican-wave/dduck-mexican-wave.py

https://www.codewars.com/kata/58f5c63f1e26ecda7e000029

feat(codewars/6kyu/mexican-wave.[js, py])

---

leetcode/easy/1475._Final_Prices_With_a_Special_Discount_in_a_Shop/myunsikbeom.js

[Easy]1475. Final Prices With a Special Discount in a Shop

[Easy]1475. Final Prices With a Special Discount in a Shop

---

leetcode/easy/1460._Make_Two_Arrays_Equal_by_Reversing_Sub-arrays/myunsikbeom.js
leetcode/easy/1480._Running_Sum_of_1d_Array/myunsikbeom.js

[Easy]1460. Make Two Arrays Equal by Reversing Sub-arrays

[Easy]1460. Make Two Arrays Equal by Reversing Sub-arrays

---

codewars/6kyu/give-me-a-diamond/dduck-give-me-a-diamond.js
codewars/6kyu/give-me-a-diamond/dduck-give-me-a-diamond.py

https://www.codewars.com/kata/5503013e34137eeeaa001648/

feat(codewars/6kyu/give-me-a-diamond.[js, py])

---

codewars/6kyu/reverse-or-rotate/dduck-reverse-or-rotate.js
codewars/6kyu/reverse-or-rotate/dduck-reverse-or-rotate.py

https://www.codewars.com/kata/56b5afb4ed1f6d5fb0000991

feat(codewars/6kyu/reverse-or-rotate.[js, py])

---

codewars/6kyu/title-case/dduck-title-case.js
codewars/6kyu/title-case/dduck-title-case.py

https://www.codewars.com/kata/5202ef17a402dd033c000009

feat(codewars/6kyu/title-case.[js, py])

---

leetcode/medium/11_container_with_most_water/runaway.js

https://leetcode.com/problems/container-with-most-water/

[leetcode-medium, js] 11. Container With Most Water

---

codewars/6kyu/tortoise-racing/dduck-tortoise-racing.js
codewars/6kyu/tortoise-racing/dduck-tortoise-racing.py

https://www.codewars.com/kata/55e2adece53b4cdcb900006c/train/javascript

feat(codewars/6kyu/tortoise-racing.[js, py])

---

codewars/6kyu/ip-validation/dduck-ip-validation.js
codewars/6kyu/ip-validation/dduck-ip-validation.py

https://www.codewars.com/kata/515decfd9dcfc23bb6000006

feat(codewars/6kyu/ip-validation.[js, py])

---

leetcode/easy/520_detect_capital/dduck-520_detect_capital.js
leetcode/easy/520_detect_capital/dduck-520_detect_capital.py

it's for review https://github.com/google-gazzza/algorithm/pull/1109/files

feat(leetcode/easy/520_detect_capital.[js, py])

---

codewars/6kyu/take-a-number-and-sum-its-digits/dduck-take-a-number-and-sum-its-digits.js
codewars/6kyu/take-a-number-and-sum-its-digits/dduck-take-a-number-and-sum-its-digits.py

https://www.codewars.com/kata/5626b561280a42ecc50000d1

feat(codewars/6kyu/take-a-number-and-sum-its-digits.[js, py])

---

leetcode/easy/917_reverse_only_letters/leedy1.java

https://leetcode.com/problems/reverse-only-letters/submissions/

[Easy] 917. Reverse Only Letters

---

leetcode/medium/12_integer_to_roman/runaway.js

https://leetcode.com/problems/integer-to-roman/

[leetcode-medium, js] 12. Integer to Roman

---

codewars/6kyu/weird-string-case/dduck-weird-string-case.js
codewars/6kyu/weird-string-case/dduck-weird-string-case.py

https://www.codewars.com/kata/52b757663a95b11b3d00062d/

feat(codewars/6kyu/weird-string-case.[js, py])

---

codewars/6kyu/camel-case-method/dduck-camel-case-method.js
codewars/6kyu/camel-case-method/dduck-camel-case-method.py

https://www.codewars.com/kata/587731fda577b3d1b0001196/

feat(codewars/6kyu/camel-case-method.[js, py])

---

leetcode/easy/1460._Make_Two_Arrays_Equal_by_Reversing_Sub-arrays/myunsikbeom.js
leetcode/medium/1476._Subrectangle_Queries

[Mideum]1476._Subrectangle_Queries

[Mideum]1476._Subrectangle_Queries

---

leetcode/easy/1512._Number_of_Good_Pairs
leetcode/medium/1476._Subrectangle_Queries

[Easy]Create 1512._Number_of_Good_Pairs

[Easy]Create 1512._Number_of_Good_Pairs

---

leetcode/easy/1290_convert_binary_number_in_a_linked_list_to_integer/awdsza.js
leetcode/easy/1684_Count_the_Number_of_Consistent_Strings/awdsza.js
leetcode/easy/1688_Count of Matches in Tournament/awdsza.js
leetcode/easy/1844_Replace All Digits with Characters/awdsza.js

leetcode/easy/1844_Replace All Digits with Characters/awdsza.js
leetcode/easy/1688_Count of Matches in Tournament/awdsza.js
leetcode/easy/1684_Count_the_Number_of_Consistent_Strings/awdsza.js
leetcode/easy/1290_convert_binary_number_in_a_linked_list_to_integer/awdsza.js

awdsza.js update

---

leetcode/easy/1603_Design_Parking_System/awdsza.js

create 1603. Design Parking System

create 1603. Design Parking System By awdsza.js

---

leetcode/medium/1551_Minimum_Operations_to_Make_Array_Equal/awdsza.js

1551. Minimum Operations to Make Array Equal Create File (awdsza.js)

1551. Minimum Operations to Make Array Equal Create File (awdsza.js)

---

leetcode/easy/1710_maximun_units_on_a_truck/yalla.java

[EASY] 1710. Maximum Units on a Truck

---

leetcode/hard/1206_design_skiplist/koronya.js

https://en.wikipedia.org/wiki/Skip_list
Skip List라는거에 대해서 처음 접했고, 처음 구현해봄...
몇시간만의 코딩테스트 문제로, Red-Black Tree를 구현하여라...는
너무 복잡해서 나오기가 힘들겠지만
이와 같은 SkipList를 구현하여라는 나올 수도 있지 않을까 생각이...-_-;
일단, 1차 시도라 돌아가는데 의의를 두고,
추후에 더 깔끔하게 리팩토링을 해봐야지 라고 생각을 합니다!

[Hard] 1206. Design Skiplist

---

leetcode/easy/283_move_zeroes/leedy1.java

https://leetcode.com/problems/move-zeroes/

[Easy] 283. Move Zeroes

---

codewars/4kyu/sudoku-solution-validator/dduck-sudoku-solution-validator.js
codewars/4kyu/sudoku-solution-validator/dduck-sudoku-solution-validator.py

https://www.codewars.com/kata/529bf0e9bdf7657179000008

feat(codewars/4kyu/sudoku-solution-validator.[js, py])

---

codewars/6kyu/help-the-bookseller/dduck-help-the-bookseller.js
codewars/6kyu/help-the-bookseller/dduck-help-the-bookseller.py

https://www.codewars.com/kata/54dc6f5a224c26032800005c/

feat(codewars/6kyu/help-the-bookseller.[js, py])
